import type { TSchema } from '@sinclair/typebox';
import { ErrorEnvelope, Ok } from './common.ts';
import * as saves from './saves.ts';
import * as lineage from './lineage.ts';
import * as purchases from './purchases.ts';
import * as grants from './grants.ts';
import * as liveops from './liveops.ts';
import * as inbox from './inbox.ts';
import * as boards from './leaderboards.ts';
import * as telemetry from './telemetry.ts';
import * as ach from './achievements.ts';
import * as admin from './admin.ts';
import * as health from './health.ts';

export type RouteAuth = 'public' | 'player' | 'admin' | 'ops' | 'beacon' | 'lab';
export type RouteMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';

export interface RouteDef {
  /** Stable id used by fixtures, OpenAPI operationId and clients. */
  id: string;
  method: RouteMethod;
  path: string;
  auth: RouteAuth;
  feature: string;
  summary: string;
  body?: TSchema;
  query?: TSchema;
  params?: TSchema;
  response: TSchema;
  /** Admin scope required (auth=admin). */
  adminScope?: 'read' | 'support' | 'grant' | 'publish' | 'restore' | 'erase';
  /** Step-up: token iat ≤ 5 min (§4.2). */
  stepUp?: boolean;
  /** Extra documented status codes beyond 200 and the error envelope defaults. */
  statuses?: number[];
}

const MUTATING: ReadonlyArray<RouteMethod> = ['POST', 'PUT', 'DELETE'];
export const isMutation = (r: RouteDef): boolean => MUTATING.includes(r.method);

export const ROUTES: readonly RouteDef[] = [
  // health
  {
    id: 'health.live',
    method: 'GET',
    path: '/health',
    auth: 'public',
    feature: 'health',
    summary: 'Liveness',
    response: health.HealthResponse,
  },
  {
    id: 'health.ready',
    method: 'GET',
    path: '/health/ready',
    auth: 'public',
    feature: 'health',
    summary: 'Readiness (db, migrations, secrets, admin keys)',
    response: health.ReadyResponse,
    statuses: [503],
  },
  {
    id: 'health.ops',
    method: 'GET',
    path: '/health/ops',
    auth: 'ops',
    feature: 'health',
    summary: 'Ops snapshot from the 15-minute rollup; ?assert=page|warn returns 503 on issues',
    query: health.OpsQuery,
    response: health.OpsSnapshotResponse,
    statuses: [503],
  },

  // saves
  {
    id: 'saves.write',
    method: 'PUT',
    path: '/v1/saves',
    auth: 'player',
    feature: 'saves',
    summary: 'Append a snapshot (200 always with a disposition)',
    body: saves.SaveWriteBody,
    response: saves.SaveWriteResult,
  },
  {
    id: 'saves.beacon',
    method: 'POST',
    path: '/v1/saves/beacon',
    auth: 'beacon',
    feature: 'saves',
    summary: 'Teardown write; auth inside a text/plain body',
    body: saves.SaveBeaconBody,
    response: saves.SaveWriteResult,
  },
  {
    id: 'saves.current',
    method: 'GET',
    path: '/v1/saves/current',
    auth: 'player',
    feature: 'saves',
    summary: 'Anchor snapshot (or empty) + pendingQuarantine',
    query: saves.CurrentQuery,
    response: saves.SaveCurrentResponse,
  },
  {
    id: 'saves.history',
    method: 'GET',
    path: '/v1/saves/history',
    auth: 'player',
    feature: 'saves',
    summary: 'Snapshot history for the active (or given) generation',
    query: saves.SaveHistoryQuery,
    response: saves.SaveHistoryResponse,
  },
  {
    id: 'saves.blob',
    method: 'GET',
    path: '/v1/saves/history/:seq/blob',
    auth: 'player',
    feature: 'saves',
    summary: 'Blob by seq',
    params: saves.SeqParams,
    response: saves.SaveBlobResponse,
    statuses: [404],
  },

  // lineage
  {
    id: 'lineage.restart',
    method: 'POST',
    path: '/v1/lineage/restart',
    auth: 'player',
    feature: 'lineage',
    summary: 'Open a restart generation (CAS on expectedGeneration)',
    body: lineage.LineageRestartBody,
    response: lineage.GenerationReceipt,
    stepUp: true,
    statuses: [409],
  },
  {
    id: 'lineage.restoreToSeq',
    method: 'POST',
    path: '/v1/lineage/restoreToSeq',
    auth: 'player',
    feature: 'lineage',
    summary: 'Player restore-to-point → new generation seeded from seq',
    body: lineage.LineageRestoreToSeqBody,
    response: lineage.GenerationReceipt,
    stepUp: true,
    statuses: [409],
  },
  {
    id: 'lineage.reattach',
    method: 'POST',
    path: '/v1/lineage/reattach',
    auth: 'player',
    feature: 'lineage',
    summary: 'server_behind recovery (operator-enabled)',
    body: lineage.LineageReattachBody,
    response: lineage.GenerationReceipt,
    stepUp: true,
    statuses: [409],
  },

  // purchases
  {
    id: 'purchases.verify',
    method: 'POST',
    path: '/v1/purchases/verify',
    auth: 'player',
    feature: 'purchases',
    summary: 'Verify a signed receipt; business key = provider token',
    body: purchases.PurchaseVerifyBody,
    response: purchases.PurchaseVerifyResult,
  },
  {
    id: 'purchases.mine',
    method: 'GET',
    path: '/v1/purchases/mine',
    auth: 'player',
    feature: 'purchases',
    summary: 'My purchases + pendingAdjustments',
    response: purchases.PurchasesMineResponse,
  },
  {
    id: 'purchases.ackAdjustments',
    method: 'POST',
    path: '/v1/purchases/adjustments/ack',
    auth: 'player',
    feature: 'purchases',
    summary: 'Ack applied adjustments',
    body: purchases.AdjustmentsAckBody,
    response: purchases.AdjustmentsAckResult,
  },

  // grants
  {
    id: 'grants.pending',
    method: 'GET',
    path: '/v1/grants/pending',
    auth: 'player',
    feature: 'grants',
    summary: 'Pending grants',
    response: grants.GrantsPendingResponse,
  },
  {
    id: 'grants.claim',
    method: 'POST',
    path: '/v1/grants/claim',
    auth: 'player',
    feature: 'grants',
    summary: 'Claim a grant (idempotent by grantKey)',
    body: grants.GrantClaimBody,
    response: grants.GrantClaimResult,
    stepUp: true,
  },
  {
    id: 'grants.claimBatch',
    method: 'POST',
    path: '/v1/grants/claim-batch',
    auth: 'player',
    feature: 'grants',
    summary: 'Batch claim',
    body: grants.GrantClaimBatchBody,
    response: grants.GrantClaimBatchResult,
    stepUp: true,
  },
  {
    id: 'codes.redeem',
    method: 'POST',
    path: '/v1/codes/redeem',
    auth: 'player',
    feature: 'grants',
    summary: 'Redeem a campaign code',
    body: grants.CodeRedeemBody,
    response: grants.CodeRedeemResult,
  },

  // achievements / daily
  {
    id: 'achievements.me',
    method: 'GET',
    path: '/v1/achievements/me',
    auth: 'player',
    feature: 'achievements',
    summary: 'Achievement progress projection',
    response: ach.AchievementsMeResponse,
  },
  {
    id: 'achievements.evaluate',
    method: 'POST',
    path: '/v1/achievements/evaluate',
    auth: 'player',
    feature: 'achievements',
    summary: 'Evaluate criteria over ledgers/summary/journal; mint grants',
    body: ach.AchievementsEvaluateBody,
    response: ach.AchievementsEvaluateResult,
  },
  {
    id: 'daily.claim',
    method: 'POST',
    path: '/v1/daily/claim',
    auth: 'player',
    feature: 'achievements',
    summary: 'Claim the daily reward (server-stamped)',
    body: ach.DailyClaimBody,
    response: ach.DailyClaimResult,
  },

  // liveops
  {
    id: 'liveops.config',
    method: 'GET',
    path: '/v1/config',
    auth: 'public',
    feature: 'liveops',
    summary: 'Public config; per-player flags when authenticated',
    response: liveops.ConfigResponse,
  },
  {
    id: 'liveops.schedules',
    method: 'GET',
    path: '/v1/schedules',
    auth: 'public',
    feature: 'liveops',
    summary: 'Active schedule windows',
    response: liveops.SchedulesResponse,
  },
  {
    id: 'liveops.content',
    method: 'GET',
    path: '/v1/content/:kind',
    auth: 'public',
    feature: 'liveops',
    summary: 'Published content document (or bundle default)',
    params: liveops.ContentKindParams,
    response: liveops.ContentDocumentResponse,
  },

  // inbox
  {
    id: 'inbox.list',
    method: 'GET',
    path: '/v1/inbox',
    auth: 'player',
    feature: 'inbox',
    summary: 'Letters + announcements with read/claimed state',
    response: inbox.InboxResponse,
  },
  {
    id: 'inbox.read',
    method: 'POST',
    path: '/v1/inbox/read',
    auth: 'player',
    feature: 'inbox',
    summary: 'Mark letters read',
    body: inbox.InboxReadBody,
    response: Ok,
  },
  {
    id: 'inbox.feedback',
    method: 'POST',
    path: '/v1/feedback',
    auth: 'player',
    feature: 'inbox',
    summary: 'Submit feedback',
    body: inbox.FeedbackBody,
    response: inbox.FeedbackResult,
  },

  // leaderboards
  {
    id: 'boards.start',
    method: 'POST',
    path: '/v1/leaderboards/:board/start',
    auth: 'player',
    feature: 'leaderboards',
    summary: 'Start a run (server stamps started_at + seed)',
    params: boards.BoardParams,
    body: boards.RunStartBody,
    response: boards.RunStartResult,
  },
  {
    id: 'boards.submit',
    method: 'POST',
    path: '/v1/leaderboards/:board/submit',
    auth: 'player',
    feature: 'leaderboards',
    summary: 'Submit a run score',
    params: boards.BoardParams,
    body: boards.RunSubmitBody,
    response: boards.RunSubmitResult,
  },
  {
    id: 'boards.top',
    method: 'GET',
    path: '/v1/leaderboards/:board/top',
    auth: 'public',
    feature: 'leaderboards',
    summary: 'Top N (no ids)',
    params: boards.BoardParams,
    response: boards.BoardTopResponse,
  },
  {
    id: 'boards.me',
    method: 'GET',
    path: '/v1/leaderboards/:board/me',
    auth: 'player',
    feature: 'leaderboards',
    summary: 'My best + placements',
    params: boards.BoardParams,
    response: boards.BoardMeResponse,
  },
  {
    id: 'boards.claimPlacement',
    method: 'POST',
    path: '/v1/leaderboards/placements/claim',
    auth: 'player',
    feature: 'leaderboards',
    summary: 'Claim a confirmed placement',
    body: boards.PlacementClaimBody,
    response: boards.PlacementClaimResult,
  },
  {
    id: 'boards.name',
    method: 'POST',
    path: '/v1/leaderboards/name',
    auth: 'player',
    feature: 'leaderboards',
    summary: 'Set display name (moderated)',
    body: boards.DisplayNameBody,
    response: boards.DisplayNameResult,
  },

  // telemetry / journal
  {
    id: 'telemetry.integrity',
    method: 'POST',
    path: '/v1/telemetry/integrity',
    auth: 'player',
    feature: 'telemetry',
    summary: 'Allow-listed integrity events (≤20/call, daily budget)',
    body: telemetry.IntegrityBatchBody,
    response: telemetry.IntegrityBatchResult,
  },
  {
    id: 'journal.ship',
    method: 'POST',
    path: '/v1/journal',
    auth: 'player',
    feature: 'journal',
    summary: 'Ship journal entries (timer path, ≤16 KiB)',
    body: telemetry.JournalShipBody,
    response: telemetry.JournalShipResult,
  },

  // admin (separate key auth; Idempotency-Key header maps to commandId)
  {
    id: 'admin.player',
    method: 'GET',
    path: '/admin/v1/players/:playerKey',
    auth: 'admin',
    adminScope: 'read',
    feature: 'admin',
    summary: 'Player overview',
    params: admin.AdminPlayerParams,
    response: admin.PlayerOverview,
  },
  {
    id: 'admin.timeline',
    method: 'GET',
    path: '/admin/v1/players/:playerKey/timeline',
    auth: 'admin',
    adminScope: 'read',
    feature: 'admin',
    summary: 'Inspector timeline (UNION over ledgers)',
    params: admin.AdminPlayerParams,
    response: admin.TimelineResponse,
  },
  {
    id: 'admin.history',
    method: 'GET',
    path: '/admin/v1/players/:playerKey/saves',
    auth: 'admin',
    adminScope: 'read',
    feature: 'admin',
    summary: 'Save history for a player',
    params: admin.AdminPlayerParams,
    query: saves.SaveHistoryQuery,
    response: saves.SaveHistoryResponse,
  },
  {
    id: 'admin.blob',
    method: 'GET',
    path: '/admin/v1/players/:playerKey/saves/:seq/blob',
    auth: 'admin',
    adminScope: 'read',
    feature: 'admin',
    summary: 'Blob by seq (JSON viewer)',
    params: admin.AdminPlayerParams,
    response: saves.SaveBlobResponse,
    statuses: [404],
  },
  {
    id: 'admin.actions',
    method: 'GET',
    path: '/admin/v1/actions',
    auth: 'admin',
    adminScope: 'read',
    feature: 'admin',
    summary: 'admin_actions replay',
    response: admin.AdminActionsResponse,
  },
  {
    id: 'admin.deadLetters',
    method: 'GET',
    path: '/admin/v1/outbox/dead-letters',
    auth: 'admin',
    adminScope: 'read',
    feature: 'admin',
    summary: 'Outbox dead letters',
    response: admin.OutboxDeadLettersResponse,
  },
  {
    id: 'admin.letter',
    method: 'POST',
    path: '/admin/v1/letters',
    auth: 'admin',
    adminScope: 'support',
    feature: 'admin',
    summary: 'Send a support letter',
    body: inbox.AdminLetterBody,
    response: Ok,
  },
  {
    id: 'admin.announcement',
    method: 'POST',
    path: '/admin/v1/announcements',
    auth: 'admin',
    adminScope: 'publish',
    feature: 'admin',
    summary: 'Publish an announcement (schedule + segment)',
    body: inbox.AdminAnnouncementBody,
    response: liveops.PublishReceipt,
  },
  {
    id: 'admin.grant',
    method: 'POST',
    path: '/admin/v1/grants',
    auth: 'admin',
    adminScope: 'grant',
    feature: 'admin',
    summary: 'Mint a grant',
    body: admin.AdminGrantBody,
    response: admin.AdminGrantResult,
  },
  {
    id: 'admin.cohortGrant',
    method: 'POST',
    path: '/admin/v1/grants/cohort',
    auth: 'admin',
    adminScope: 'grant',
    feature: 'admin',
    summary: 'Mint for a cohort (dry-run count)',
    body: admin.AdminCohortGrantBody,
    response: admin.AdminCohortGrantResult,
  },
  {
    id: 'admin.codeCampaign',
    method: 'POST',
    path: '/admin/v1/codes/campaigns',
    auth: 'admin',
    adminScope: 'grant',
    feature: 'admin',
    summary: 'Create a code campaign',
    body: admin.AdminCodeCampaignBody,
    response: admin.AdminCodeCampaignResult,
  },
  {
    id: 'admin.adjustment',
    method: 'POST',
    path: '/admin/v1/purchases/adjustments',
    auth: 'admin',
    adminScope: 'grant',
    feature: 'admin',
    summary: 'Purchase adjustment (± referencing this admin action)',
    body: admin.AdminAdjustmentBody,
    response: admin.AdminAdjustmentResult,
  },
  {
    id: 'admin.playerFlag',
    method: 'POST',
    path: '/admin/v1/players/flags',
    auth: 'admin',
    adminScope: 'support',
    feature: 'admin',
    summary: 'Set a player flag',
    body: admin.AdminPlayerFlagBody,
    response: Ok,
  },
  {
    id: 'admin.publishFlag',
    method: 'POST',
    path: '/admin/v1/liveops/flags',
    auth: 'admin',
    adminScope: 'publish',
    feature: 'admin',
    summary: 'Publish a flag state',
    body: liveops.FlagPublishBody,
    response: liveops.PublishReceipt,
  },
  {
    id: 'admin.publishContent',
    method: 'POST',
    path: '/admin/v1/liveops/content',
    auth: 'admin',
    adminScope: 'publish',
    feature: 'admin',
    summary: 'Publish a content document (lab|prod)',
    body: liveops.ContentPublishBody,
    response: liveops.PublishReceipt,
  },
  {
    id: 'admin.revertContent',
    method: 'POST',
    path: '/admin/v1/liveops/content/revert',
    auth: 'admin',
    adminScope: 'publish',
    feature: 'admin',
    summary: 'Revert content to a version',
    body: liveops.ContentRevertBody,
    response: liveops.PublishReceipt,
  },
  {
    id: 'admin.publishSchedule',
    method: 'POST',
    path: '/admin/v1/liveops/schedules',
    auth: 'admin',
    adminScope: 'publish',
    feature: 'admin',
    summary: 'Publish a schedule window',
    body: liveops.SchedulePublishBody,
    response: liveops.PublishReceipt,
  },
  {
    id: 'admin.publishSegment',
    method: 'POST',
    path: '/admin/v1/liveops/segments',
    auth: 'admin',
    adminScope: 'publish',
    feature: 'admin',
    summary: 'Publish a segment predicate',
    body: liveops.SegmentPublishBody,
    response: liveops.PublishReceipt,
  },
  {
    id: 'admin.segmentPreview',
    method: 'GET',
    path: '/admin/v1/liveops/segments/:id/preview',
    auth: 'admin',
    adminScope: 'read',
    feature: 'admin',
    summary: 'Segment preview count',
    response: liveops.SegmentPreviewResponse,
  },
  {
    id: 'admin.killSwitch',
    method: 'POST',
    path: '/admin/v1/liveops/kill-switches',
    auth: 'admin',
    adminScope: 'publish',
    feature: 'admin',
    summary: 'Kill switch per SKU/command',
    body: liveops.KillSwitchBody,
    response: liveops.PublishReceipt,
  },
  {
    id: 'admin.minBuild',
    method: 'POST',
    path: '/admin/v1/liveops/min-build',
    auth: 'admin',
    adminScope: 'publish',
    feature: 'admin',
    summary: 'Set minBuildVersion',
    body: liveops.MinBuildBody,
    response: liveops.PublishReceipt,
  },
  {
    id: 'admin.season',
    method: 'POST',
    path: '/admin/v1/leaderboards/seasons',
    auth: 'admin',
    adminScope: 'publish',
    feature: 'admin',
    summary: 'Upsert a season (draft/active/closed)',
    body: boards.SeasonUpsertBody,
    response: liveops.PublishReceipt,
  },
  {
    id: 'admin.reviewSubmission',
    method: 'POST',
    path: '/admin/v1/leaderboards/reviews',
    auth: 'admin',
    adminScope: 'support',
    feature: 'admin',
    summary: 'Review a quarantined submission',
    body: boards.SubmissionReviewBody,
    response: Ok,
  },
  {
    id: 'admin.restore',
    method: 'POST',
    path: '/admin/v1/players/restore',
    auth: 'admin',
    adminScope: 'restore',
    feature: 'admin',
    summary: 'Restore-to-seq → new generation admin_restore',
    body: admin.AdminRestoreBody,
    response: lineage.GenerationReceipt,
    statuses: [409],
  },
  {
    id: 'admin.reviewSave',
    method: 'POST',
    path: '/admin/v1/saves/reviews',
    auth: 'admin',
    adminScope: 'restore',
    feature: 'admin',
    summary: 'Promote/reject a quarantined save (terminal)',
    body: admin.AdminSaveReviewBody,
    response: admin.AdminSaveReviewResult,
  },
  {
    id: 'admin.erase',
    method: 'POST',
    path: '/admin/v1/players/erase',
    auth: 'admin',
    adminScope: 'erase',
    feature: 'admin',
    summary: 'Erase a player (generation erased + erasure ledger)',
    body: admin.AdminEraseBody,
    response: admin.AdminEraseResult,
  },
  {
    id: 'admin.outboxReplay',
    method: 'POST',
    path: '/admin/v1/outbox/replay',
    auth: 'admin',
    adminScope: 'support',
    feature: 'admin',
    summary: 'Replay an outbox row for a consumer',
    body: admin.AdminOutboxReplayBody,
    response: Ok,
  },
  {
    id: 'admin.rebuildProjection',
    method: 'POST',
    path: '/admin/v1/projections/rebuild',
    auth: 'admin',
    adminScope: 'restore',
    feature: 'admin',
    summary: 'Rebuild a pure projection from ledgers',
    body: admin.AdminRebuildProjectionBody,
    response: admin.AdminRebuildProjectionResult,
  },

  // qa (lab only)
  {
    id: 'qa.mint',
    method: 'POST',
    path: '/qa/v1/identity/mint',
    auth: 'lab',
    feature: 'qa',
    summary: 'Mint a qa_ identity token (GAME_ENV=lab only)',
    body: admin.QaMintBody,
    response: admin.QaMintResult,
  },
  {
    id: 'qa.import',
    method: 'POST',
    path: '/qa/v1/saves/import',
    auth: 'lab',
    feature: 'qa',
    summary: 'Import a sanitised snapshot as a lineage seed (manifest required)',
    body: admin.QaImportBody,
    response: admin.QaImportResult,
  },
];

export const ROUTE_BY_ID: ReadonlyMap<string, RouteDef> = new Map(ROUTES.map((r) => [r.id, r]));

export { ErrorEnvelope };
